(() => {
  const KEY='professional-english-work-v1', today=()=>new Date().toISOString().slice(0,10);
  const defaults={theme:'light',target:10,british:true,sound:true,xp:0,sessions:0,days:[],card:{},category:'All'};
  let state={...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}, view='home', deck=[], index=0, session={seen:0,correct:0,mastered:0,missed:0};
  const app=document.querySelector('#app'), toast=document.querySelector('#toast');
  const cardState=id=>state.card[id]||{difficulty:0,timesSeen:0,timesCorrect:0,timesMissed:0,masteryLevel:0,lastReviewed:null};
  const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));document.documentElement.dataset.theme=state.theme};
  const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));
  const toastIt=s=>{toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2100)};
  const stats=()=>{const cs=Object.values(state.card), seen=cs.reduce((s,c)=>s+c.timesSeen,0), correct=cs.reduce((s,c)=>s+c.timesCorrect,0), mastered=cs.filter(c=>c.masteryLevel>=3).length; return {seen,correct,mastered,accuracy:seen?Math.round(correct/seen*100):0,streak:streak()}};
  const streak=()=>{const d=[...new Set(state.days||[])].sort().reverse();let n=0,dt=new Date();for(let x of d){if(x===dt.toISOString().slice(0,10)){n++;dt.setDate(dt.getDate()-1)}else if(x!==dt.toISOString().slice(0,10))break}return n};
  const longestStreak=()=>{let days=[...new Set(state.days||[])].sort(),best=0,run=0,previous=null;days.forEach(day=>{let current=new Date(`${day}T00:00:00`);if(previous&&(current-previous===86400000))run++;else run=1;best=Math.max(best,run);previous=current});return best};
  const level=()=>{let n=Math.min(6,Math.floor(state.xp/150)+1), names=['Professional Starter','Confident Communicator','Meeting Professional','Confident Presenter','Management Communicator','Executive Communicator'];return {n,name:names[n-1],pct:Math.min(100,(state.xp%150)/1.5)}};
  const registerDay=()=>{if(!state.days.includes(today())) state.days.push(today())};
  const speak=text=>{if(!state.british||!('speechSynthesis'in window)) return; speechSynthesis.cancel();let u=new SpeechSynthesisUtterance(text);u.lang='en-GB';u.rate=.9;let v=speechSynthesis.getVoices().find(x=>x.lang==='en-GB');if(v)u.voice=v;speechSynthesis.speak(u)};
  const nav=next=>{view=next;render();app.focus()};
  const progressBar=(p)=>`<div class="progress-bar"><i style="width:${p}%"></i></div>`;
  function home(){let s=stats(),l=level();return `<section class="hero"><p class="eyebrow">COMMUNICATION PRACTICE</p><h1>Professional English<br><em>at Work</em></h1><p>Speak clearly. Sound confident. Lead professionally.</p><div class="level"><span>Level ${l.n}</span><b>${l.name}</b>${progressBar(l.pct)}<small>${state.xp} XP · ${150-(state.xp%150)} XP to next level</small></div></section><section class="goal panel"><div><span class="eyebrow">TODAY'S GOAL</span><h2>${state.target} cards</h2></div><button class="primary" data-action="daily">Start practice →</button></section><section class="metrics"><div><b>${s.seen}</b><span>Cards practised</span></div><div><b>${s.accuracy}%</b><span>Accuracy</span></div><div><b>🔥 ${s.streak}</b><span>Day streak</span></div><div><b>${s.mastered}</b><span>Mastered</span></div></section><section><div class="section-heading"><div><p class="eyebrow">TRAINING MODES</p><h2>Build fluency daily</h2></div></div><div class="mode-grid"><button data-view="practice"><b>▣</b><span>Flashcards</span><small>Learn the stronger phrase</small></button><button data-view="challenge"><b>◇</b><span>Challenge Mode</span><small>Choose the professional version</small></button><button data-view="self"><b>✎</b><span>Say It Yourself</span><small>Build your own response</small></button><button data-view="situations"><b>◈</b><span>Situations</span><small>Practice real conversations</small></button><button data-view="difficult"><b>↻</b><span>Difficult Cards</span><small>Focus where it matters</small></button><button data-view="practice"><b>≡</b><span>Categories</span><small>Filter by workplace context</small></button></div></section>`}
  function makeDeck(kind='all'){let cards=[...CARD_LIBRARY].filter(c=>state.category==='All'||c.category===state.category);if(kind==='daily'){let sorted=[...cards].sort((a,b)=>cardState(b.id).difficulty-cardState(a.id).difficulty||cardState(a.id).timesSeen-cardState(b.id).timesSeen);let difficult=sorted.filter(x=>cardState(x.id).difficulty>0).slice(0,5), medium=sorted.filter(x=>!difficult.includes(x)&&cardState(x.id).timesSeen>0).slice(0,3), fresh=sorted.filter(x=>!difficult.includes(x)&&!medium.includes(x)&&!cardState(x.id).timesSeen).slice(0,2);cards=[...difficult,...medium,...fresh];if(cards.length<state.target) cards=[...cards,...sorted.filter(x=>!cards.includes(x)).slice(0,state.target-cards.length)]}else cards.sort((a,b)=>cardState(b.id).difficulty-cardState(a.id).difficulty||Math.random()-.5);return cards.slice(0,kind==='daily'?state.target:cards.length)}
  const picker=()=>`<label class="filter">Category <select id="category"><option>All</option>${[...new Set(CARD_LIBRARY.map(c=>c.category))].sort().map(c=>`<option ${state.category===c?'selected':''}>${c}</option>`).join('')}</select></label>`;
  function practice(){if(!deck.length)deck=makeDeck('all');if(index>=deck.length)return complete('Practice complete');let c=deck[index],n=Math.min(index+1,deck.length),flipped=false;return `<section class="view-head"><div><p class="eyebrow">FLASHCARDS · ${picker()}</p><h1>Say it with confidence</h1></div><span class="count">${n} / ${deck.length}</span></section>${progressBar(n/deck.length*100)}<article class="flashcard" id="flashcard" tabindex="0" role="button" aria-label="Tap to reveal professional sentence"><div class="card-face front"><p>DON'T SAY</p><blockquote>“${esc(c.weakSentence)}”</blockquote><small>Tap to reveal a stronger alternative</small></div><div class="card-face back"><p>SAY INSTEAD</p><blockquote>“${esc(c.professionalSentence)}”</blockquote><button class="listen" data-speak="${esc(c.professionalSentence)}">◖ Listen</button></div></article><div class="answer-actions"><button class="outline" data-rate="again">× Practice again</button><button class="primary" data-rate="know">✓ I know it</button></div><p class="hint">Tap the card to flip it.</p>`}
  function complete(title){let accuracy=session.seen?Math.round(session.correct/session.seen*100):0;return `<section class="complete"><div class="completion-icon">✓</div><p class="eyebrow">SESSION COMPLETE</p><h1>${title}</h1><p>Consistent practice turns good ideas into professional language.</p><div class="metrics"><div><b>${accuracy}%</b><span>Accuracy</span></div><div><b>${session.mastered}</b><span>Mastered</span></div><div><b>${session.missed}</b><span>Needs practice</span></div></div><div class="best-phrase"><p class="eyebrow">BEST PHRASE TODAY</p><blockquote>“Based on what we’ve seen, my recommendation would be…”</blockquote></div><button class="primary full" data-view="home">Back to home</button></section>`}
  function challenge(){if(!deck.length)deck=makeDeck('all');if(index>=Math.min(deck.length,10))return complete('Challenge complete');let c=deck[index],wrong=CARD_LIBRARY.filter(x=>x.id!==c.id).sort(()=>Math.random()-.5).slice(0,2).map(x=>x.professionalSentence), opts=[c.professionalSentence,...wrong].sort(()=>Math.random()-.5);return `<section class="view-head"><div><p class="eyebrow">CHALLENGE MODE</p><h1>Choose the professional version</h1></div><span class="count">${index+1} / 10</span></section><div class="scenario panel"><span>MANAGEMENT MEETING</span><p>You are speaking during a management meeting.</p></div><article class="weak-prompt"><p>Instead of:</p><blockquote>“${esc(c.weakSentence)}”</blockquote><h2>Which sounds more professional?</h2></article><div class="choices">${opts.map((o,i)=>`<button data-choice="${esc(o)}" data-correct="${esc(c.professionalSentence)}"><b>${'ABC'[i]}</b>${esc(o)}</button>`).join('')}</div><div id="feedback"></div>`}
  function situations(){let examples=[['Management Meeting',"You're wrong.","I'd challenge that assumption slightly."],['Presentation','Let me explain.','Let me give you some context.'],['HR Meeting','Who is responsible?','Where does the accountability sit?'],['Project Discussion','Forget this for now.','Perhaps we can park this for the moment.'],['Decision Making','I think maybe we should…','Based on what we’ve seen, my recommendation would be…']];return `<section class="view-head"><div><p class="eyebrow">REAL WORK SITUATIONS</p><h1>Language for the moments that matter</h1></div></section><div class="situation-list">${examples.map(x=>`<article class="situation panel"><span>${x[0]}</span><p class="dont">DON'T SAY · “${x[1]}”</p><p class="instead">SAY INSTEAD · “${x[2]}”</p><button class="listen" data-speak="${esc(x[2])}">◖ Listen</button></article>`).join('')}</div><button class="primary full" data-view="self">Try saying it yourself →</button>`}
  function self(){let c=CARD_LIBRARY[49];return `<section class="view-head"><div><p class="eyebrow">SAY IT YOURSELF</p><h1>Put it in your own words</h1></div></section><article class="weak-prompt"><p>Replace this weak sentence:</p><blockquote>“${c.weakSentence}”</blockquote><h2>How would you say this professionally?</h2></article><textarea id="selfAnswer" placeholder="Write your professional version here…"></textarea><button class="primary full" data-action="reveal">Reveal recommended answer</button><div id="selfReveal"></div>`}
  function difficult(){let cards=CARD_LIBRARY.filter(c=>cardState(c.id).difficulty>0).sort((a,b)=>cardState(b.id).difficulty-cardState(a.id).difficulty);return `<section class="view-head"><div><p class="eyebrow">NEEDS MORE PRACTICE</p><h1>Focus on the phrases that will make the difference</h1></div></section>${cards.length?`<div class="situation-list">${cards.map(c=>`<article class="situation panel"><span>${c.category} · ${cardState(c.id).difficulty} practice signal${cardState(c.id).difficulty>1?'s':''}</span><p class="dont">DON'T SAY · “${c.weakSentence}”</p><p class="instead">SAY INSTEAD · “${c.professionalSentence}”</p></article>`).join('')}</div>`:`<div class="empty panel"><b>Nothing here yet</b><p>Choose “Practice again” on a flashcard and it will return here for focused review.</p><button class="primary" data-view="practice">Start flashcards</button></div>`}`}
  function progress(){let s=stats(),cats=[...new Set(CARD_LIBRARY.map(c=>c.category))];return `<section class="view-head"><div><p class="eyebrow">MY PROGRESS</p><h1>Progress with purpose</h1></div></section><section class="metrics report"><div><b>${CARD_LIBRARY.length}</b><span>Total cards</span></div><div><b>${s.mastered}</b><span>Mastered</span></div><div><b>${CARD_LIBRARY.filter(c=>cardState(c.id).difficulty>0).length}</b><span>Needs practice</span></div><div><b>${s.accuracy}%</b><span>Overall accuracy</span></div><div><b>🔥 ${s.streak}</b><span>Current streak</span></div><div><b>${longestStreak()}</b><span>Longest streak</span></div><div><b>${state.sessions}</b><span>Practice sessions</span></div></section><section class="panel category-progress"><p class="eyebrow">BY CATEGORY</p>${cats.map(cat=>{let list=CARD_LIBRARY.filter(c=>c.category===cat),p=Math.round(list.filter(c=>cardState(c.id).masteryLevel>=3).length/list.length*100);return `<div><span>${cat}</span><b>${p}%</b>${progressBar(p)}</div>`}).join('')}</section>`}
  function settings(){return `<section class="view-head"><div><p class="eyebrow">SETTINGS</p><h1>Make practice yours</h1></div></section><section class="settings panel"><label>Daily card target<select id="target">${[5,10,15,20].map(n=>`<option ${state.target===n?'selected':''}>${n}</option>`).join('')}</select></label><label><span>British English pronunciation</span><input id="british" type="checkbox" ${state.british?'checked':''}><i></i></label><label><span>Sound</span><input id="sound" type="checkbox" ${state.sound?'checked':''}><i></i></label><label><span>Dark mode</span><input id="dark" type="checkbox" ${state.theme==='dark'?'checked':''}><i></i></label><hr><button class="danger" id="reset">Reset all progress</button><small>This clears saved practice data only. Your cards remain available.</small></section>`}
  function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));app.innerHTML=({home,practice,challenge,situations,self,difficult,progress,settings}[view]||home)();save()}
  document.addEventListener('click',e=>{let el=e.target.closest('button,[data-view],#flashcard');if(!el)return;if(el.dataset.view){deck=[];index=0;nav(el.dataset.view);return}if(el.id==='flashcard'){el.classList.toggle('flipped');return}if(el.dataset.speak){speak(el.dataset.speak);return}if(el.dataset.action==='daily'){deck=makeDeck('daily');index=0;session={seen:0,correct:0,mastered:0,missed:0};state.sessions++;nav('practice');return}if(el.dataset.rate){let c=deck[index],d=cardState(c.id);d.timesSeen++;d.lastReviewed=today();session.seen++;registerDay();if(el.dataset.rate==='know'){d.timesCorrect++;d.masteryLevel=Math.min(5,d.masteryLevel+1);d.difficulty=Math.max(0,d.difficulty-1);session.correct++;state.xp+=d.difficulty===0&&d.masteryLevel>=3?20:10;if(d.masteryLevel>=3)session.mastered++}else{d.timesMissed++;d.difficulty++;d.masteryLevel=Math.max(0,d.masteryLevel-1);session.missed++}state.card[c.id]=d;index++;render();return}if(el.dataset.choice){let good=el.dataset.choice===el.dataset.correct;document.querySelectorAll('.choices button').forEach(x=>x.disabled=true);el.classList.add(good?'correct':'wrong');document.querySelector('#feedback').innerHTML=`<div class="feedback ${good?'good':'bad'}"><b>${good?'✓ Correct':'× Try again'}</b><p>${good?'This phrasing is clear, measured, and directs attention to action.':'The strongest option is the phrasing that is specific, calm, and solution-oriented.'}</p></div>`;let c=deck[index],d=cardState(c.id);d.timesSeen++;session.seen++;registerDay();if(good){d.timesCorrect++;d.masteryLevel++;session.correct++;state.xp+=15}else{d.timesMissed++;d.difficulty++;session.missed++}state.card[c.id]=d;setTimeout(()=>{index++;render()},1400);return}if(el.dataset.action==='reveal'){document.querySelector('#selfReveal').innerHTML=`<article class="recommended"><p class="eyebrow">RECOMMENDED ANSWER</p><blockquote>“Based on what we’ve seen, my recommendation would be to proceed with this approach.”</blockquote><div class="answer-actions"><button class="outline" data-self="almost">△ Almost</button><button class="outline" data-self="practice">× Need practice</button><button class="primary" data-self="good">✓ Good</button></div></article>`;return}if(el.dataset.self){state.xp+=el.dataset.self==='good'?10:0;registerDay();toastIt('Saved to your progress');save();return}if(el.id==='reset'){if(confirm('Reset all saved progress? This cannot be undone.')){state={...defaults};deck=[];index=0;save();nav('home')}return}});
  document.addEventListener('change',e=>{if(e.target.id==='category'){state.category=e.target.value;deck=[];render()}if(e.target.id==='target'){state.target=+e.target.value;save()}if(e.target.id==='british'){state.british=e.target.checked;save()}if(e.target.id==='sound'){state.sound=e.target.checked;save()}if(e.target.id==='dark'){state.theme=e.target.checked?'dark':'light';save()}});document.querySelector('#themeToggle').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';save()};
  if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));render();
})();
